const mockLeads = [
  {
    _id: "lead_1",
    first_name: "Rahul",
    last_name: "Sharma",
    email: "rahul.sharma@example.com",
    mobile: "+91 9876543210",
    website: "www.rahultech.com",
    reason: "Admission Inquiry",
    course: "Web Development Masterclass",
    teacher_department: "Computer Science Dept",
    message: "I would like to inquire about the course duration, batch timings, and fee structure for the upcoming Web Development Masterclass.",
    created_at: "2026-08-30T10:15:00Z",
    updated_at: "2026-08-30T10:15:00Z",
  },
  {
    _id: "lead_2",
    first_name: "Priya",
    last_name: "Patel",
    email: "priya.patel@gmail.com",
    mobile: "+91 9823456789",
    website: "www.priyadesigns.in",
    reason: "Career Counseling",
    course: "UI/UX Design Certification",
    teacher_department: "Design & Arts Dept",
    message: "Seeking career counseling and details regarding the UI/UX Design course curriculum and placement assistance.",
    created_at: "2026-08-29T14:45:00Z",
    updated_at: "2026-08-29T14:45:00Z",
  },
  {
    _id: "lead_3",
    first_name: "Amit",
    last_name: "Verma",
    email: "amit.verma@yahoo.com",
    mobile: "+91 9911223344",
    website: "www.amitv.org",
    reason: "Course Information",
    course: "Data Science & AI Specialization",
    teacher_department: "Data Science Dept",
    message: "Could you please share the syllabus and prerequisite requirements for the Data Science & AI Specialization program?",
    created_at: "2026-08-28T09:30:00Z",
    updated_at: "2026-08-28T09:30:00Z",
  },
  {
    _id: "lead_4",
    first_name: "Sneha",
    last_name: "Gupta",
    email: "sneha.g@domain.com",
    mobile: "+91 9765432109",
    website: "www.snehagupta.dev",
    reason: "General Inquiry",
    course: "Full Stack MERN Bootcamp",
    teacher_department: "Information Technology Dept",
    message: "Hi, I am interested in joining the Full Stack MERN Bootcamp. Are weekend classes available?",
    created_at: "2026-08-27T16:20:00Z",
    updated_at: "2026-08-27T16:20:00Z",
  },
  {
    _id: "lead_5",
    first_name: "Vikram",
    last_name: "Singh",
    email: "vikram.singh@outlook.com",
    mobile: "+91 9654321098",
    website: "www.vikramcorp.com",
    reason: "Corporate Training",
    course: "Cloud Computing & DevOps",
    teacher_department: "Cloud Engineering Dept",
    message: "Looking for customized corporate training sessions in Cloud Computing and DevOps for a team of 15 engineers.",
    created_at: "2026-08-25T11:10:00Z",
    updated_at: "2026-08-25T11:10:00Z",
  },
  {
    _id: "lead_6",
    first_name: "Ananya",
    last_name: "Roy",
    email: "ananya.roy@gmail.com",
    mobile: "+91 9543210987",
    website: "www.ananyaroy.com",
    reason: "Admission Inquiry",
    course: "Digital Marketing & SEO Pro",
    teacher_department: "Management & Marketing Dept",
    message: "Please let me know the upcoming batch starting dates and discount offers for early enrollment.",
    created_at: "2026-08-22T08:00:00Z",
    updated_at: "2026-08-22T08:00:00Z",
  },
];

export default mockLeads;
