const express = require("express");
const authRoutes = require("./authRoutes");
const router = express.Router();

router.use("/auth", authRoutes);

const cityRoutes = require("./cityRoutes");
const mediaRoutes = require("./mediaRoutes");
const tagRoutes = require("./tagRoutes");
const userRoutes = require("./userRoutes");
const roleRoutes = require("./roleRoutes");
const materialRoutes = require("./materialRoutes");
const skillsRoutes = require("./skillsRoutes");
const couponRoutes = require("./couponRoutes");
const ageRoutes = require("./ageRoutes");
const productRoutes = require("./productRoutes");
const productGalleryRoutes = require("./productGalleryRoutes");
const bannerRoutes = require("./bannerRoutes");
const brandRoutes = require("./brandRoutes");
const categoryRoutes = require("./categoryRoutes");
const characterRoutes = require("./characterRoutes");
const colorRoutes = require("./colorRoutes");
const addressTypeRoutes = require("./addressTypeRoutes");
const deliveryAddressRoutes = require("./deliveryAddressRoutes");
const leadsRoutes = require("./leadsRoutes");
const productwishlistRoutes = require("./productwishlistRoutes");
const productCartRoutes = require("./productCartRoutes");
const commodityRoutes = require("./commodityRoutes");
const shippingclassRoutes = require("./shippingclassRoutes");
const shippingmethodRoutes = require("./shippingmethodRoutes");
const shippingRoutes = require("./shippingRoutes");
const productOrderRoutes = require("./productOrderRoutes");
const profileImageRoutes = require("./profileImageRoutes");
const supportTicketRoutes = require("./supportTicketRoutes");
const blogRoutes = require("./blogRoutes");
const reviewRoutes = require("./reviewRoutes");

// All routes grouped under /api
router.use("/city", cityRoutes);
router.use("/media", mediaRoutes);
router.use("/tag", tagRoutes);
router.use("/role", roleRoutes);
router.use("/user", userRoutes);
router.use("/material", materialRoutes);
router.use("/skills", skillsRoutes);
router.use("/coupon", couponRoutes);
router.use("/age", ageRoutes);
router.use("/product", productRoutes);
router.use("/gallery", productGalleryRoutes);
router.use("/banner", bannerRoutes);
router.use("/brand", brandRoutes);
router.use("/category", categoryRoutes);
router.use("/character", characterRoutes);
router.use("/color", colorRoutes);
router.use("/addressType", addressTypeRoutes);
router.use("/deliveryAddress", deliveryAddressRoutes);
router.use("/leads", leadsRoutes);
router.use("/wishlist", productwishlistRoutes);
router.use("/cart", productCartRoutes);
router.use("/commodity", commodityRoutes);
router.use("/shippingclass", shippingclassRoutes);
router.use("/shippingmethod", shippingmethodRoutes);
router.use("/shipping", shippingRoutes);
router.use("/order", productOrderRoutes);
router.use("/profile-image", profileImageRoutes);
router.use("/support-ticket", supportTicketRoutes);
router.use("/blog", blogRoutes);
router.use("/review", reviewRoutes);

module.exports = router;
